name: Release

on:
  workflow_dispatch:
    inputs:
      TAG_VERSION:
        description: "Tag version"
        required: true
        type: string

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.6'
      
      - name: Build
        run: |
          GOOS=${{ matrix.os }}
          GOARCH=${{ matrix.arch }}
          make build

      - name: Upload binary
        uses: actions/upload-artifact@v5
        with:
          name: opa_redis_${{ matrix.os }}_${{ matrix.arch }}
          parh: dist/opa_redis_${{ matrix.os }}_${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v6
        with:
          path: dist
      
      - name: List built files
        run: ls -lh dist/**

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.TAG_VERSION }}
          name: Release ${{ github.event.inputs.TAG_VERSION }}
          files: |
            dist/**/opa_redis_*







